name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  {% raw -%}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  {%- endraw %}
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Tap homebrew-empyrealsdk
        run: |
          brew tap empyrealapp/homebrew-empyrealsdk
          brew install empctl

      - name: Init service
        run: |
          empctl services init --name {{ cookiecutter.service_name }} --ignore-exists
        env:
          {% raw -%}
          EMPCTL_API_TOKEN: ${{ secrets.EMPCTL_API_TOKEN }}
          {%- endraw %}

      - name: Build and Deploy
        run: |
          {% raw -%}
          empctl build --tag ${{ github.sha }} \
          {% endraw -%}
          --push \
          --deploy \
          --service {{ cookiecutter.service_name }}
        env:
          {% raw -%}
          EMPCTL_API_TOKEN: ${{ secrets.EMPCTL_API_TOKEN }}
          {%- endraw %}
